"""
Check prose against the writing rules in CLAUDE.md and docs/ste-writing.md.

Run this before a commit, over whatever the change touched:

    python tools/ste_lint.py lib/buzz/scope.py tests/test_scope_math.py
    python tools/ste_lint.py --changed              # every line the diff added
    python tools/ste_lint.py --changed --base main

It exits 1 when it finds something, so it can sit beside `ruff check .` in the
pre-commit sequence, and 2 when it could not run at all - a `--base` that names
no commit, say.  A gate that cannot run must not report a pass.

-------------------------------------------------------------------------------
What counts as prose
-------------------------------------------------------------------------------

Rules about sentences have no business being applied to code, so this extracts
prose rather than scanning raw lines:

  * Python comments, through `tokenize`.
  * Python docstrings, through `ast`.
  * The message arguments of `raise`, `assert`, and `logger.*`, which is the
    text a reader meets while something is wrong.  An f-string arrives as
    separate pieces, so those are rejoined with `{}` standing in for each
    value.  Without that, "could not start ffmpeg at {path}" reads as a
    sentence ending in a preposition, and the tool reports a fault it invented.
  * Markdown outside fenced code blocks.

Identifiers, expressions and command syntax are never examined, per
docs/ste-writing.md's own "What this applies to".

-------------------------------------------------------------------------------
Two modes
-------------------------------------------------------------------------------

STRICT covers text a reader meets while stuck: error messages, log lines, and
assertion messages.  Every rule applies, including the length caps, the ban on
semicolons and contractions, and the ban on ending a sentence with a
preposition.

FLAVORED covers comments, docstrings and Markdown.  The sentence discipline
applies; the length caps and vocabulary limits do not.  See ste-writing.md's
"Two modes" for why the two differ.

-------------------------------------------------------------------------------
Where the spacing rule applies
-------------------------------------------------------------------------------

Two spaces after a period is a house rule for prose somebody reads as prose:
comments, docstrings, and end-user documentation.  It is not enforced in
CHANGELOG.md, CLAUDE.md, or schema.json, which are records and machine-readable
sources rather than prose, and which have never followed it - 329 instances at
the time of writing.  Enforcing it there would mean a large cosmetic diff that
improves nothing.  Every other rule still applies to those files.

docs/ste-writing.md is exempt for a different reason: it was adapted from an
outside skill under the MIT License, and its wording is closer to that source
than to this project's own.  Reflowing 45 sentences of borrowed text to suit a
house rule the source never claimed to follow would only obscure what was
changed here and what was not.

Two other exemptions are narrower.  A rule book (CLAUDE.md, ste-writing.md) is
exempt from the vocabulary rules, because it quotes each of those words in order
to ban it, and every quotation reported as a fault.  CHANGELOG.md's released
sections are not read at all: they describe what shipped, the published release
notes were lifted from them verbatim, and ste-writing.md's override 3 leaves them
alone.  The [Unreleased] section above them is still checked.

-------------------------------------------------------------------------------
One rule that is not about prose
-------------------------------------------------------------------------------

Every Markdown file under docs-notebook/ has to open with an attribution line,
"Generated by ...", because that folder holds measurements and decisions written
largely by a model and a reader judging a figure needs to know what produced it.
It sits here rather than in somebody's memory because the rule was broken within
minutes of being written, in the README that states it.  This is the only check
that reads a file's position rather than its sentences.

-------------------------------------------------------------------------------
What this cannot do
-------------------------------------------------------------------------------

It checks the rules that can be checked mechanically.  Three of the rules in
ste-writing.md's self-lint cannot be, and still need a person: sentence
fragments, passive voice where the actor is known, and an `-ing` form used as
the main verb.  A clean run means no mechanical fault was found.  It does not
mean the prose is good, and it cannot make a hollow paragraph true.
"""

import argparse
import ast
import io
import json
import re
import subprocess
import sys
import tokenize
from dataclasses import dataclass, replace
from pathlib import Path

# Assistant tells, banned outright by CLAUDE.md.
BANNED = re.compile(r'\b(genuine|genuinely|load-bearing|is real|are real|lands?|landed)\b', re.I)
MARKETING = re.compile(
    r'\b(seamless|robust|powerful|cutting-edge|effortless|world-class'
    r'|next-generation|revolutionary)\b', re.I)
# British spellings this project is converting as it touches them; see
# ste-writing.md's override 3.
BRITISH = re.compile(
    r'\b\w*(centre|colour|behaviour|synchronis|quantis|neighbour|analyse'
    r'|organis|licence|initialis|normalis)\w*\b', re.I)
# Prefer the short common word.
WORDY = {
    'commence': 'start', 'initiate': 'start', 'utilize': 'use', 'leverage': 'use',
    'facilitate': 'help',
    'prior to': 'before', 'subsequent to': 'after', 'regarding': 'about',
    'concerning': 'about', 'obtain': 'get',
    'demonstrate': 'show', 'demonstrates': 'show', 'additionally': 'also',
    'furthermore': 'also', 'moreover': 'also',
}
WORDY_RE = re.compile(r'\b(' + '|'.join(sorted(WORDY, key=len, reverse=True)) + r')\b', re.I)
CONTRACTION = re.compile(r"\b\w+(?:n't|'re|'ll|'ve|'d|'m)\b")
PREPOSITIONS = frozenset(
    ('at', 'by', 'for', 'from', 'in', 'of', 'on', 'to', 'with', 'into', 'about', 'over'))

# ste-writing.md's strict caps: 20 words for an instruction, 25 for a description.
# A message is a description unless it is written as a command, which is a
# distinction this cannot draw, so it uses the looser of the two.
STRICT_WORD_CAP = 25

# Files exempt from the two-space rule only.  See the module docstring.
SPACING_EXEMPT = ('CHANGELOG.md', 'CLAUDE.md', 'ste-writing.md', '.json')
# Files that quote the banned words in order to ban them.
RULE_BOOKS = ('CLAUDE.md', 'ste-writing.md')

# CHANGELOG.md's released sections describe what shipped, and the published release
# notes were lifted from them verbatim, so ste-writing.md's override 3 leaves their
# wording alone.  Everything from the first version heading down is therefore out of
# scope; the [Unreleased] section above it is still being written and is checked.
RELEASED_HEADING = re.compile(r'^## \[\d')


@dataclass(frozen=True)
class Finding:
    path: str
    line: int
    rule: str
    detail: str
    text: str
    strict: bool
    # Last line of the prose this came from.  A docstring spans many lines, and
    # --changed has to notice an edit anywhere inside one, not only on the line the
    # docstring opens.  Reporting by the opening line alone hid a real fault during
    # this tool's own first run against the branch that introduced it.
    end_line: int = 0

    def touches(self, added: set[int]) -> bool:
        """Whether any line of the prose behind this finding was added.

        A finding whose line could not be worked out reports as touched.  Dropping
        it would be the silent kind of miss this tool exists to prevent, and the
        cost of the other choice is one finding a reader has to place by hand.
        """
        if self.line <= 0:
            return True
        return any(line in added for line in range(self.line, max(self.end_line, self.line) + 1))

    def render(self) -> str:
        mode = 'strict' if self.strict else 'flavored'
        excerpt = ' '.join(self.text.split())[:100]
        return f'{self.path}:{self.line}: {self.rule} ({mode}) - {self.detail}\n    {excerpt}'


# A period that closes a sentence, as against one inside "2.5 ms" or "config.py".
# What excludes those two is the whitespace every user of this pattern requires
# after it, since neither a decimal nor a dotted name has any.  The lookbehind is
# for the remaining case, a one-letter initial: "N. Johnson" is one sentence.
#
# The lookbehind used to reject any capital or digit, which was far too broad.  It
# read "the gate is 97.  Coverage fell" as a single sentence, so the strict word cap
# was applied to the pair and the trailing-preposition check only ever saw the last
# clause of a multi-sentence message.
SENTENCE_END = r'(?<!\b[A-Z])[.!?]'
# The "1." opening a numbered step is not a sentence end.  Only a figure at the
# start of its own line is a marker, so a sentence that closes on a number is
# still checked.
LIST_MARKER = re.compile(r'(?:^|\n)\s*\d+$')


def sentences(text: str) -> list[str]:
    """Split prose into sentences, leaving decimals and initials intact."""
    flat = ' '.join(text.split())
    return [part.strip() for part in re.split(SENTENCE_END + r'\s+', flat) if part.strip()]


def _check_spacing(path: str, line: int, text: str, strict: bool) -> list[Finding]:
    """One space after a period, where two belong."""
    if path.endswith(SPACING_EXEMPT):
        return []
    # The lookahead is the whole test: one space and then a capital is the fault.
    # Two spaces do not match it, and neither does a newline, which is a paragraph
    # break rather than a missing space.
    found = []
    for match in re.finditer(SENTENCE_END + r'(?= [A-Z])', text):
        before = text[:match.start()].rstrip()
        if before.endswith(('e.g', 'i.e', '.')):
            continue
        if LIST_MARKER.search(text[:match.start()]):
            continue
        excerpt = text[max(0, match.start() - 30):match.start() + 30]
        found.append(Finding(path, line, 'one space after a period', excerpt.strip(),
                             text, strict))
    return found


def _distinct(pattern: re.Pattern[str], text: str) -> list[str]:
    """Every different string `pattern` matches in `text`, in the order they appear.

    Reporting one match per line meant fixing a fault and meeting the next one on the
    following run, so a clean result after an edit only proved the first match had
    gone.  Repeats of the same word collapse to one finding, because they get fixed
    together anyway.
    """
    return list(dict.fromkeys(match.group(0) for match in pattern.finditer(text)))


def _check_words(path: str, line: int, text: str, strict: bool) -> list[Finding]:
    """Banned words, marketing adjectives, British spellings, and wordy choices.

    A rule book is exempt from all four.  CLAUDE.md and ste-writing.md quote every
    one of these words in order to ban it, so each rule here fires on the sentence
    that outlaws it: the line naming the two British spellings this project is
    converting is itself two British spellings.  Reporting a wall of findings on
    the one file nobody may edit blind is worse than reporting none.
    """
    if path.endswith(RULE_BOOKS):
        return []
    found = []
    for pattern, rule in ((BANNED, 'banned word'), (MARKETING, 'marketing adjective'),
                          (BRITISH, 'British spelling')):
        found += [Finding(path, line, rule, f'"{word}"', text, strict)
                  for word in _distinct(pattern, text)]
    # The wordy list is a vocabulary restriction, and ste-writing.md applies those in
    # strict mode only.  Flavored prose carries reasoning a strict vocabulary cannot
    # express, which is the reason that override exists.  Checking it everywhere had
    # the tool enforcing a rule its own specification exempts.
    if strict:
        found += [Finding(path, line, 'wordy',
                          f'"{word}" -> "{WORDY[word.lower()]}"', text, strict)
                  for word in _distinct(WORDY_RE, text)]
    return found


def _check_dashes(path: str, line: int, text: str, strict: bool) -> list[Finding]:
    """Em dashes anywhere, and en dashes used as punctuation rather than as a range.

    A tight en dash between two figures is a numeric range, which is typography
    rather than the dash CLAUDE.md bans.  A spaced one is being used as a dash.
    """
    if '—' in text:
        return [Finding(path, line, 'em dash', 'use a spaced hyphen', text, strict)]
    if re.search(r'(?<![0-9A-Za-z])–|–(?![0-9A-Za-z])', text):
        return [Finding(path, line, 'en dash', 'use a spaced hyphen', text, strict)]
    return []


def _check_strict(path: str, line: int, text: str) -> list[Finding]:
    """The rules that apply only to text a reader meets while stuck."""
    found = [Finding(path, line, 'contraction', f'"{word}"', text, True)
             for word in _distinct(CONTRACTION, text)]
    if ';' in text:
        found.append(Finding(path, line, 'semicolon', 'write two sentences', text, True))
    for sentence in sentences(text):
        words = sentence.split()
        if len(words) > STRICT_WORD_CAP:
            found.append(Finding(path, line, 'over the strict cap',
                                 f'{len(words)} words, cap is {STRICT_WORD_CAP}',
                                 sentence, True))
        # A sentence closing on an interpolated value ends with the value, not with
        # the word before it.  "Could not start ffmpeg at {path}" is correct prose,
        # and flagging it would push the writer into rewording a good message.
        if re.search(r'\{\}[^A-Za-z]*$', sentence):
            continue
        tail = re.sub(r'[^A-Za-z]+$', '', sentence).split()
        if tail and tail[-1].lower() in PREPOSITIONS:
            found.append(Finding(path, line, 'ends with a preposition',
                                 f'"{tail[-1]}"', sentence, True))
    return found


def check(path: str, line: int, text: str, strict: bool) -> list[Finding]:
    """Every rule that applies to one piece of prose."""
    found = _check_dashes(path, line, text, strict)
    found += _check_words(path, line, text, strict)
    found += _check_spacing(path, line, text, strict)
    if strict:
        found += _check_strict(path, line, text)
    return found


# ---------------------------------------------------------------------------
# Extracting prose
# ---------------------------------------------------------------------------

# A comment that is a directive to a tool rather than a sentence to a reader.
DIRECTIVES = ('noqa', 'type:', 'pragma', '!', 'ruff:', 'fmt:')
LOG_METHODS = frozenset(('debug', 'info', 'warning', 'error', 'exception', 'critical'))
# Below this a "message" is a label or a fragment rather than prose, and the
# sentence rules say nothing useful about it.
MIN_MESSAGE_WORDS = 4


def _strict_strings(node: ast.AST | None) -> list[tuple[int, int, str]]:
    """The message of one raise, assert, or logger call, rebuilt from its pieces.

    The pieces are gathered depth first through `ast.iter_child_nodes`, which
    yields a node's children in the order the source wrote them.  `ast.walk` is
    breadth first and returned them scrambled: `f"could not read {path} " + "and
    the fallback was empty"` came back with the two halves reversed, which both
    hides a real fault at the join and invents one that is not there.

    An interpolated value is not descended into.  It is code, and a dictionary key
    or a repr inside it is not part of the sentence the reader sees.
    """
    if node is None:
        return []
    parts: list[str] = []
    first: int | None = None
    last = 0

    def gather(inner: ast.AST) -> None:
        nonlocal first, last
        if isinstance(inner, ast.Constant) and isinstance(inner.value, str):
            parts.append(inner.value)
            first = first if first is not None else inner.lineno
            last = max(last, inner.end_lineno or inner.lineno)
        elif isinstance(inner, ast.FormattedValue):
            parts.append('{}')
        else:
            for child in ast.iter_child_nodes(inner):
                gather(child)

    gather(node)
    joined = ''.join(parts)
    if first is None or len(joined.split()) < MIN_MESSAGE_WORDS:
        return []
    return [(first, last, joined)]


def python_prose(source: str) -> list[tuple[int, int, str, bool]]:
    """(start, end, text, strict) for every comment, docstring and message."""
    items: list[tuple[int, int, str, bool]] = []
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        if token.type == tokenize.COMMENT:
            body = token.string.lstrip('#').strip()
            if body and not body.startswith(DIRECTIVES):
                items.append((token.start[0], token.end[0], body, False))
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            doc = ast.get_docstring(node, clean=True)
            if doc:
                literal = node.body[0]
                items.append((literal.lineno, literal.end_lineno or literal.lineno,
                              doc, False))
        # The message only, never the whole statement.  An assert's test expression
        # holds strings of its own, and reading those as part of the message glued
        # `assert state == 'unlocked', 'the analyzer did not lock in the time given
        # at'` into one string ending in "unlocked", which hides the trailing
        # preposition the rule exists to catch.
        holders: list[ast.AST | None] = []
        if isinstance(node, ast.Raise):
            holders = [node.exc]
        elif isinstance(node, ast.Assert):
            holders = [node.msg]
        elif (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                and node.func.attr in LOG_METHODS):
            holders = list(node.args)
        for holder in holders:
            items.extend((start, end, text, True)
                         for start, end, text in _strict_strings(holder))
    return items


def markdown_prose(source: str) -> list[tuple[int, int, str, bool]]:
    """(line, line, text, False) for every Markdown line outside a fenced block."""
    items, fenced = [], False
    for number, line in enumerate(source.splitlines(), 1):
        if line.lstrip().startswith('```'):
            fenced = not fenced
            continue
        # An indented block is code too, by Markdown's own four-space rule.
        if not fenced and line.strip() and not line.startswith('    '):
            items.append((number, number, line, False))
    return items


def json_prose(source: str) -> list[tuple[int, int, str, bool]]:
    """The operator-facing text in a schema: title, description, and x-notes."""
    texts: list[str] = []

    def walk(node: object) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                if key in ('title', 'description') and isinstance(value, str):
                    texts.append(value)
                elif key == 'x-notes' and isinstance(value, list):
                    texts.extend(v for v in value if isinstance(v, str))
                else:
                    walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(json.loads(source))
    items = []
    # `walk` visits the document in the order it was written, so the search can run
    # forward from the last hit.  Without that, two fields sharing a description
    # both report against the first one's line.
    cursor = 0
    for text in texts:
        at = _locate(source, text, cursor)
        if at < 0:
            items.append((0, 0, text, False))
            continue
        cursor = at + 1
        start = source[:at].count('\n') + 1
        items.append((start, start, text, False))
    return items


def _locate(source: str, text: str, start_at: int) -> int:
    """Where a decoded JSON string sits in its source file, or -1.

    The decoded string is not what the file holds.  A quote or a backslash inside
    it was written escaped, so searching for the decoded form misses every string
    that carries one, and the schema's `ssh-keygen -N ""` note is exactly that.
    Under --changed a miss is worse than a wrong line number: the item reports at
    line 0, and an edit to it then goes unchecked.  `json.dumps` re-escapes the
    text the way the file wrote it.  The decoded form is still tried afterwards,
    since a file is free to escape more than the minimum.
    """
    for candidate in (json.dumps(text)[1:-1], text):
        at = source.find(candidate, start_at)
        if at >= 0:
            return at
    return -1


EXTRACTORS = {'.py': python_prose, '.md': markdown_prose, '.json': json_prose}


NOTEBOOK_DIR = 'docs-notebook/'
NOTEBOOK_ATTRIBUTION = 'Generated by'


def _check_attribution(name: str, source: str) -> list[Finding]:
    """A notebook document written by a model has to say so on its first line.

    Mechanical because it is easy to forget, and forgetting is invisible.  The rule
    was broken within minutes of being written, in the README that states it, by
    thinking of that file as structure rather than as content.  A reader deciding how
    far to trust a measurement needs to know what produced it, and a model should not
    be able to read its own document back later as though a person had.

    Every file in the folder is checked rather than only the generated ones, because
    nothing can tell the two apart after the fact.  The cost of that falls on a
    person who writes one by hand and has to add a line naming themselves, which is
    a smaller cost than a generated document that quietly passes as theirs.
    """
    if not name.startswith(NOTEBOOK_DIR) or not name.endswith('.md'):
        return []
    first = source.lstrip().splitlines()[0] if source.strip() else ''
    if first.startswith(NOTEBOOK_ATTRIBUTION):
        return []
    return [Finding(name, 1, 'missing attribution',
                    f'{NOTEBOOK_DIR} files open with "{NOTEBOOK_ATTRIBUTION} ..."',
                    first or '(empty file)', False)]


def lint_file(path: Path) -> list[Finding]:
    """Every finding in one file, or none for a type this does not read."""
    extract = EXTRACTORS.get(path.suffix)
    if extract is None:
        return []
    name = path.as_posix()
    source = path.read_text(encoding='utf-8')
    released = _released_from(source) if path.name == 'CHANGELOG.md' else sys.maxsize
    findings = _check_attribution(name, source)
    for start, end, text, strict in extract(source):
        if start >= released:
            continue
        for finding in check(name, start, text, strict):
            findings.append(replace(finding, end_line=end))
    return findings


def _released_from(source: str) -> int:
    """The first line of CHANGELOG.md's released sections, or a line past the end."""
    for number, line in enumerate(source.splitlines(), 1):
        if RELEASED_HEADING.match(line):
            return number
    return sys.maxsize


def changed_lines(base: str) -> dict[str, set[int]]:
    """Line numbers the working tree and its commits have added since `base`."""
    result = subprocess.run(['git', 'diff', '-U0', base], capture_output=True,
                            text=True, encoding='utf-8')
    # A failed diff gives an empty stdout, which parses as "nothing changed" and
    # reports the run clean.  For a gate that runs before every commit, a mistyped
    # base ref must not read as a pass.
    if result.returncode != 0:
        reason = (result.stderr.strip().splitlines() or ['git printed no reason'])[0]
        raise RuntimeError(
            f'git diff against "{base}" failed: {reason}\n'
            f'The base has to be a commit in this repository.  Pass an existing '
            f'branch, tag, or commit to --base, or drop --changed and name the '
            f'files to check.')
    diff = result.stdout
    added: dict[str, set[int]] = {}
    path = None
    for line in diff.splitlines():
        if line.startswith('+++ b/'):
            path = line[6:]
        elif line.startswith('@@') and path:
            match = re.search(r'\+(\d+)(?:,(\d+))?', line)
            start, count = int(match.group(1)), int(match.group(2) or 1)
            added.setdefault(path, set()).update(range(start, start + count))
    return added


# ---------------------------------------------------------------------------
# Sentence fragments, as an advisory rather than a rule
# ---------------------------------------------------------------------------
#
# ste-writing.md lists three rules this tool cannot check: sentence fragments,
# passive voice, and an -ing form used as the main verb.  This closes part of the
# first one, and only part, which is why --fragments is off by default.
#
# A fragment is a clause with no finite verb, so detecting one means knowing which
# words are verbs, and that list has no end.  Measured over lib/, tools/, scripts/
# and tests/, a first pass flagged 16 sentences of which roughly 9 were real, and
# every false alarm was a verb the list did not know: draws, differed, stood, agree,
# opened, accounts.  Those are in it now, which lowers the noise without closing the
# gap, because the next unknown verb is always one sentence away.  The list is a net
# and not a proof.
#
# Nine real findings for seven false alarms is a good trade when somebody chose to
# look, and a bad one in a gate that blocks a commit, because a tool that calls
# correct prose wrong teaches people to ignore it.  So this runs when asked and never
# otherwise, and the reading job in CLAUDE.md stays.

# Openings that begin a fragment far more often than they begin a sentence: an
# adjective, an adverb, a bare participle or a negation, with no subject behind it.
# Narrowing to these took the false alarms from 210 to 7.
FRAGMENT_OPENERS = frozenset("""
worth not deliberately distinct good better best useful helpful similar same
unlike rather hence hardly merely simply purely largely mostly chiefly enough
measured taken given seen done said noted chosen written built made plenty
""".split())

# Finite verb forms.  Incomplete by construction; see above.
FINITE_VERBS = frozenset("""
is are was were be been being am has have had do does did can could will would
shall should must may might needs need makes make takes take gives give gets get
goes go comes come sets set puts put reads read writes write holds hold keeps keep
wants want means mean leaves leave says say shows show knows know sits sit runs run
costs cost counts count moves move works work fails fail adds add uses use
depends depend arrives arrive reaches reach covers cover dominates dominate
beats beat stays stay drops drop falls fall rises rise helps help lets let
turns turn starts start ends end finds find picks pick sees see asks ask
calls call passes pass carries carry produces produce returns return
expects expect treats treat applies apply refuses refuse reports report
records record scales scale divides divide matches match measures measure
maps map derives derive folds fold lies lie exists exist remains remain
contains contain includes include requires require allows allow draws draw
changes change appears appear seems seem becomes become differs differ agrees agree
stands stand stood opens open opened accounts account sends send sent
differed agreed drew opened stayed dropped counted measured showed lasted
""".split())

_WORD = re.compile(r"[A-Za-z][A-Za-z'-]*")

# Tokens for the subjectless-opener test below, which needs to see numbers.  "Set 0
# to record every event" opens with an imperative, and dropping the 0 would leave
# "Set to", which reads exactly like the participle this is hunting.
_TOKEN = re.compile(r"[A-Za-z][A-Za-z'-]*|\d+")

# What a subjectless sentence opens with: a past participle, then a preposition.
#
# "Snapped to the nearest step the tuner offers" has no noun doing the snapping.  The
# fragment test above cannot see it, because it asks whether the sentence contains a
# finite verb anywhere and this one contains two, both in subordinate clauses.  A
# main clause with no subject is a different defect from a clause with no verb.
#
# The two-word shape is what keeps it quiet.  A participle alone flags every
# imperative, since "set", "read" and "put" are both; requiring a preposition next
# separates "Snapped to the nearest step" from "Set 0 to record every event".
# Measured over schema.json it found four real cases and no false ones.
_PARTICIPLE_IRREGULARS = frozenset("""
built written chosen taken given made kept held left sent drawn shown known seen
done found
""".split())

_AFTER_A_PARTICIPLE = frozenset("""
to on in by from at for with into onto against over under after before through
across rather as than about
""".split())


def looks_subjectless(sentence: str) -> bool:
    """Whether this sentence opens with a participle and never says what did it.

    Advisory, like the fragment test, and for the same reason: deciding whether a
    word is a participle or an imperative needs a dictionary this does not have.
    """
    # The notebook attribution line is subjectless on purpose, and _check_attribution
    # above requires it in exactly this form.  One rule in this file demanding a
    # sentence another reports as a fault would make the tool argue with itself, the
    # same reason a rule book is exempt from the vocabulary rules it quotes.
    if sentence.lstrip().startswith(NOTEBOOK_ATTRIBUTION):
        return False
    # A label is not a sentence.  "Calibrated at gain (dB)" is a field title, a noun
    # phrase by house convention, and the giveaway is that it carries no terminal
    # punctuation where every real description ends in a period.  Without this the
    # check reports the house style as an error, which is how a tool teaches people
    # to ignore it.
    if not sentence.rstrip().endswith(('.', '!', '?')):
        return False
    tokens = _TOKEN.findall(sentence)
    if len(tokens) < 3:
        return False
    first, second = tokens[0], tokens[1].lower()
    participle = (first[:1].isupper()
                  and (first.lower().endswith('ed')
                       or first.lower() in _PARTICIPLE_IRREGULARS))
    return participle and second in _AFTER_A_PARTICIPLE


def looks_like_a_fragment(sentence: str) -> bool:
    """Whether this reads as a clause with no finite verb.

    Two gates, both narrow on purpose.  The sentence has to open with a word that
    usually starts a fragment, and it has to contain no finite verb anywhere.  Either
    alone flags far too much: the opener test alone catches every participial phrase
    that turns out to have a main verb later, and the verb test alone flagged 210
    sentences across this repo.
    """
    words = _WORD.findall(sentence)
    if len(words) < 3 or words[0].lower() not in FRAGMENT_OPENERS:
        return False
    return not any(word.lower() in FINITE_VERBS for word in words)


def fragments_in(path: Path) -> list[Finding]:
    """Advisory findings for one file: fragments, and openers with no subject.

    For Python, a comment RUN is joined into one block before splitting into
    sentences, unlike python_prose, which yields a line at a time.  A line at a time
    is right for every other rule here and useless for this one: half a sentence has
    no verb in it, so every wrapped comment would report as a fragment.

    The first sentence of a Python block is skipped.  A docstring summary and a
    config option's label are both noun phrases by convention in this project, so
    flagging them would report the house style as an error.

    schema.json goes through its own extractor.  It was excluded entirely until a
    subjectless description reached the setup screen and the sample config, which is
    prose an operator reads and this tool never looked at.  A JSON string is one
    whole sentence run already, so it needs no joining, and none of it is a summary
    line, so none of it is skipped.

    Markdown is left alone, and that is a gap rather than a decision.  markdown_prose
    yields a line at a time, so a wrapped paragraph arrives as halves of sentences and
    every one of them reads as a fragment: three such false alarms came straight out
    of docs-notebook/ the first time this was pointed at them.  Joining a Markdown
    paragraph the way _joined_blocks joins a comment run would close it.
    """
    if path.suffix == '.py':
        blocks = [(line, text, 1) for line, text in _joined_blocks(path.read_text(encoding='utf-8'))]
    elif path.suffix == '.json':
        blocks = [(line, text, 0)
                  for line, _end, text, _strict in json_prose(path.read_text(encoding='utf-8'))]
    else:
        return []
    found = []
    for line, text, skip in blocks:
        for position, sentence in enumerate(sentences(text)):
            if position < skip:
                continue
            if looks_like_a_fragment(sentence):
                found.append(Finding(path.as_posix(), line,
                                     'reads as a sentence fragment (advisory)',
                                     sentence[:70], sentence, False))
            elif looks_subjectless(sentence):
                found.append(Finding(path.as_posix(), line,
                                     'opens with a participle and names no subject '
                                     '(advisory)',
                                     sentence[:70], sentence, False))
    return found


def _joined_blocks(source: str) -> list[tuple[int, str]]:
    """(line, text) for each run of comment lines and each docstring."""
    blocks: list[tuple[int, str]] = []
    run: list[str] = []
    start = 0
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        if token.type == tokenize.COMMENT:
            body = token.string.lstrip('#').strip()
            if body and not body.startswith(DIRECTIVES):
                start = start or token.start[0]
                run.append(body)
                continue
        if token.type in (tokenize.NL, tokenize.COMMENT):
            continue
        if run:
            blocks.append((start, ' '.join(run)))
            run, start = [], 0
    # No flush is needed after the loop.  tokenize always ends with an ENDMARKER,
    # which is neither NL nor COMMENT, so the branch above closes the last run even
    # in a file that is nothing but comments.
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            doc = ast.get_docstring(node, clean=True)
            if doc:
                blocks.append((node.body[0].lineno, doc))
    return blocks


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument('paths', nargs='*', help='files to check')
    parser.add_argument('--changed', action='store_true',
                        help='check only the lines the diff against --base added')
    parser.add_argument('--base', default='HEAD',
                        help='what --changed compares against (default: HEAD)')
    parser.add_argument('--fragments', action='store_true',
                        help='also look for sentence fragments (advisory, noisy)')
    args = parser.parse_args(argv)

    # Checking nothing must not read as finding nothing.  Without this, a bare
    # invocation printed "clean: 0 file(s)" and exited 0, which is the same hole
    # the --base failure below was fixed for, and what CLAUDE.md's "a gate that
    # cannot run must not report a pass" is about.
    if not args.paths and not args.changed:
        print('This run has nothing to check, because no paths were named and '
              '--changed was not passed.  Name the files to check, or pass '
              '--changed to take them from the diff.  Checking nothing is not the '
              'same as finding nothing, so this exits 2 rather than reporting '
              'clean.', file=sys.stderr)
        return 2

    added: dict[str, set[int]] = {}
    paths = [Path(p) for p in args.paths]
    if args.changed:
        try:
            added = changed_lines(args.base)
        except RuntimeError as failure:
            print(failure, file=sys.stderr)
            return 2
        if not paths:
            paths = [Path(p) for p in added]

    findings, missing = [], []
    for path in paths:
        if not path.exists():
            missing.append(path)
            print(f'{path}: no such file', file=sys.stderr)
            continue
        checks = lint_file(path)
        if args.fragments:
            checks += fragments_in(path)
        for finding in checks:
            if added and not finding.touches(added.get(finding.path, set())):
                continue
            findings.append(finding)

    for finding in sorted(findings, key=lambda f: (f.path, f.line)):
        print(finding.render())
    if findings:
        print(f'\n{len(findings)} finding(s). See docs/ste-writing.md.')
    # A named path that is not there means the run covered less than it was asked
    # to, so it cannot report clean and must not be mistaken for a pass.
    if missing:
        print(f'{len(missing)} named path(s) did not exist, so this run checked '
              'less than it was asked to.  Fix the paths and run it again.',
              file=sys.stderr)
        return 2
    if findings:
        return 1
    print(f'clean: {len(paths)} file(s)')
    return 0


if __name__ == '__main__':                      # pragma: no cover -- CLI entry point
    sys.exit(main())
